version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - cashflow-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - treasuryflow-net      

  treasury-flow-api:
    build:
      context: ./TreasuryFlow.Api
      dockerfile: Dockerfile
    container_name: treasury-flow-api
    environment:
      - ConnectionStrings__TreasuryFlowDb=Server=sqlserver,1433;Database=treasury-flow;User ID=sa;Password=1q2w3e4r@#$;TrustServerCertificate=True;
      - RabbitMQ__Connection=amqp://admin:123456@rabbitmq:5672
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - cashflow-net
      
volumes:
  postgres_data:
  pgadmin_data:

networks:
  cashflow-net:
    driver: bridge
